version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk2

  # logstash:
  #   build: logstash/
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk2
  #   depends_on:
  #     - elasticsearch

  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk2
    depends_on:
      - elasticsearch

  appserver:
    build: appserver/
    networks:
      - elk2
    depends_on:
      - elasticsearch

networks:

  elk2:
    driver: bridge
